#!/usr/bin/env bash

# Uncomment line below to show help each time flumi-pass is run
# fluminurs --help

# feel free to change the location of the nusnetID file
NUSNETID_FILE=~/.nusnet.txt

if [[ ! -f "$NUSNETID_FILE" ]]; then
	read -r -p "Username (include the nusstu\ prefix) :" NUSNETID 
    echo "$NUSNETID" > "$NUSNETID_FILE"
fi

read -r USERNAME < "$NUSNETID_FILE"

# "nusnet" is the name of the password file stored by "pass"
# feel free to change the name
PASSWORD="$(pass nusnet)"


# for executing the options and arguments that fluminurs supports
# also answers the prompts that fluminurs asks for on startup, without saving the password
# in plaintext
if [[ -z "$1" ]]; then
	printf "%s\n%s\nn\n" "$USERNAME" "$PASSWORD" | fluminurs
elif [[ -z "$2" ]]; then
	printf "%s\n%s\nn\n" "$USERNAME" "$PASSWORD" | fluminurs "$1"
else
	printf "%s\n%s\nn\n" "$USERNAME" "$PASSWORD" | fluminurs "$1" "$2"
fi

